---

pipeline:
  build:
    image: busybox
    commands:
      - echo $PWD
      - ls
      - find .

#services:
#  postgres:
#    image: postgres:9.4.5
#    environment:
#      - POSTGRES_USER=myapp
